### ISSUE TITLE
How to config mutil email cc , bcc and replyto_mail in this package

### ISSUE THREAD

**Issue by quochieuhcm** [adrianorsouza/codeigniter-phpmailer#1]
How to config mutil email cc , bcc and replyto_mail in this package

**Comment by adrianorsouza** [comment]
@quochieuhcm this is not an issue within this package, you should only open an issue when you find a problem or bug with this package.

Anyway you can use the config file to set all options you need, take look at this sample:

https://github.com/adrianorsouza/codeigniter-phpmailer#sample-mail_configphp

To enable the ability to send cc/bcc you must set `mail_setBcc` or `mail_setCc` to `true` beyond define your email address.
